### ISSUE TITLE
add termination check in define/rec/match

### ISSUE THREAD

**Issue by stchang** [stchang/cur#3]

**Comment by wilbowma** [comment]
This is related to the trust issues we've discussed previously. Looks like `define/rec/match` is an extension to the trusted core, since it's defining new reduction rules rather than elaborating into eliminators (and, thus, circumventing termination guarantees given via eliminators).

1. Extensions to the trusted core should not be in `sugar.rkt`; those should be syntactic sugar that need not be trusted.
2. We need some way to make such extensions more obvious/less possible out side of declared modules.

**Comment by stchang** [comment]
Yes, agree with both points. `define/rec/match` is in `stdlib/sugar` because it was initially sugar for `match`, but it should be moved now.

**Comment by wilbowma** [comment]
Any reason it can't be sugar for match? Need some way to transform recursive calls into references to the inductive hypothesis/accumulator. My earlier solution was a bit of a hack but seems sound in principle.

**Comment by stchang** [comment]
1. The earlier solution did not work for functions that recursively called itself with more than one argument.
    
    Examples like `minus` and `equal` were impossible to write.

2. When working interactively, it doesnt scale beyond tiny examples.

    Eg, if I use the `simpl` tactic, it must stop at function calls. So something like `(plus n m)` in the goal should not reduce further, until `induction` or something else gives it concrete arguments.

    But if `plus` is defined as just `define` + `match`  you'll wind up with a bunch of nested lambdas and elims, which is pretty much unreadable. In other words, the recursive calls will unroll too eagerly in most cases.

    To fix this, `define/rec/match` needs to be its own form that defines a new reduction, and cannot be just sugar.

**Comment by stchang** [comment]
fixed with https://github.com/stchang/cur/commit/4c2c0fa2c62e0c243ed563e0f8717b5615c1affb

see also sized type experiment in ff244197b16e7f2eb7d34fadcf5bfcb5af7f2435 and `define/rec/match*`
